language: node

node:
  - 6.5.0

sudo: required

services:
  - docker

install:
 - NODE_ENV=development npm install

script:
  - NODE_ENV=development istanbul cover ./node_modules/mocha/bin/_mocha --report lcovonly -- -R spec && cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js && rm -rf ./coverage
